FROM node:18-alpine AS base

# Install dependencies only when needed
# FROM base AS deps

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
# RUN apk add — no-cache g++ make py3-pip libc6-compat

WORKDIR /app
COPY package*.json ./

RUN npm install

COPY . .

# COPY --from=base /app/node_modules ./node_modules
# COPY --from=base /app/package.json ./package.json
# COPY --from=base /app/.next ./.next
# COPY --from=base /app/src ./src
# COPY --from=base /app .

EXPOSE 3000

CMD ["npm", "run", "dev"]